version: '3.9'
services:
  rabbitmq:
    image: rabbitmq:management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - oc_rabbitmq:/var/lib/rabbitmq

volumes:
  oc_rabbitmq:
    external: true

